locations:
- name: caba
  display_name: CABA (Ciudad de Buenos Aires)
  query_suffix: "en Ciudad Aut\xF3noma de Buenos Aires, Argentina"
- name: gba_norte
  display_name: GBA Norte
  query_suffix: en Gran Buenos Aires Norte, Argentina
- name: cordoba_ar
  display_name: "C\xF3rdoba, Argentina"
  query_suffix: "en C\xF3rdoba, Argentina"
- name: rosario
  display_name: Rosario, Argentina
  query_suffix: en Rosario, Santa Fe, Argentina
- name: mendoza
  display_name: Mendoza, Argentina
  query_suffix: en Mendoza, Argentina
- name: la_pampa
  display_name: La Pampa, Argentina
  query_suffix: en La Pampa, Argentina
- name: argentina_all
  display_name: Toda Argentina
  query_suffix: en Argentina
- name: cdmx
  display_name: "CDMX (Ciudad de M\xE9xico)"
  query_suffix: "en Ciudad de M\xE9xico, M\xE9xico"
- name: mexico_all
  display_name: "Todo M\xE9xico"
  query_suffix: "en M\xE9xico"
- name: santiago_cl
  display_name: Santiago de Chile
  query_suffix: en Santiago, Chile
- name: sao_paulo
  display_name: "S\xE3o Paulo, Brasil"
  query_suffix: "em S\xE3o Paulo, Brasil"
- name: brasil_all
  display_name: Todo Brasil
  query_suffix: em Brasil
- name: madrid
  display_name: "Madrid, Espa\xF1a"
  query_suffix: "en Madrid, Espa\xF1a"
- name: barcelona
  display_name: "Barcelona, Espa\xF1a"
  query_suffix: "en Barcelona, Espa\xF1a"
- name: manhattan
  display_name: Manhattan, NY
  query_suffix: in Manhattan, New York
- name: brooklyn
  display_name: Brooklyn, NY
  query_suffix: in Brooklyn, New York
- name: queens
  display_name: Queens, NY
  query_suffix: in Queens, New York
- name: bronx
  display_name: Bronx, NY
  query_suffix: in the Bronx, New York
- name: staten_island
  display_name: Staten Island, NY
  query_suffix: in Staten Island, New York
- name: usa_all
  display_name: All United States
  query_suffix: in the United States
